name: Publish and Deploy

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: build & publish
      run: |
        docker login -u jayfong -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        docker buildx build --platform ${{ steps.buildx.outputs.platforms }} --push -t jayfong/yapi:beta .
